AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys Postgres using Portworx Volumes
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: KubeManifestConfig
      Parameters:
      - KubeManifestLambdaArn
      - KubeConfigPath
      - KubeConfigKmsContext
    - Label:
        default: Portworx Database Configuration
      Parameters:
      - PostgresContainerVersion
      - PostgresContainerPort
      - PostgresPVCSize
      - PortworxReplicationLevel
      - PortworxSnapshotSchedule
    ParameterLabels:
      KubeManifestLambdaArn:
        default: The KubeManifest Lambda Arn used to interact with the EKS Cluster
      KubeConfigPath:
        default: The s3 path to the KubeConfig.
      KubeConfigKmsContext:
        default: The KMS context used to access the KubeConfig
      PostgresContainerVersion:
        default: Container Image to use for Portworx
      PostgresContainerPort:
        default: Container port for Postgres container
      PostgresPVCSize:
        default: The Volume size in Gi for Postgres.
      PortworxReplicationLevel:
        default: Replication level of Portworx volume
      PortworxSnapshotSchedule:
        default: The snapshot schedule string for the Portworx volume
Parameters:
  KubeManifestLambdaArn:
    Description: The AWS kubectl Lamnda Arn used to interact with the EKS Cluster
    Type: String
  KubeConfigPath:
    Description: The s3 path to the KubeConfig.
    Type: String
  KubeConfigKmsContext:
    Description: The KMS context used to access the KubeConfig.
    Type: String
    Default: "EKSQuickStart"
  PostgresContainerVersion:
    Type: String
    Default: "postgres:10.1"
    Description: Container Image to use for Portworx
  PostgresContainerPort:
    Type: Number
    Default: 5432
    Description: Container port for Postgres container
  PostgresPVCSize:
    Type: String
    Default: "5Gi"
    Description: The Volume size in Gi for Postgres.
  PortworxReplicationLevel:
    Type: String
    Default: "1"
    Description: Replication level of Portworx volume
  PortworxSnapshotSchedule:
    Type: String
    Default: "periodic=60,10"
    Description: Accepted formats (periodic=mins,snaps-to-keep), (daily=hh:mm,snaps-to-keep) (weekly=weekday@hh:mm,snaps-to-keep) (monthly=day@hh:mm,snaps-to-keep) snaps-to-keep is optional. Periodic, Daily, Weekly and Monthly keep last 5, 7, 5 and 12 snapshots by default respectively.
Resources:
  PostgresStorageClassStack:
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      # The lambda function that executes the manifest against the cluster. This is created in one of the parent stacks
      ServiceToken: !Ref KubeManifestLambdaArn
      # S3 path to the encrypted config file eg. s3://my-bucket/kube/config.encrypted
      KubeConfigPath: !Ref KubeConfigPath
      # context for KMS to use when decrypting the file
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      # Replication level for PVCs using this storage class
      PortworxReplicationLevel: !Ref PortworxReplicationLevel
      # Snapshot Schedule
      PortworxSnapshotSchedule: !Ref PortworxSnapshotSchedule
      # Kubernetes manifest
      Manifest: !Sub |
        kind: StorageClass
        apiVersion: storage.k8s.io/v1beta1
        metadata:
            name: px-postgres-sc
        provisioner: kubernetes.io/portworx-volume
        parameters:
           repl: '${PortworxReplicationLevel}'
           snap_schedule: '${PortworxSnapshotSchedule}'
  PostgresPVCStack:
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      # The lambda function that executes the manifest against the cluster. This is created in one of the parent stacks
      ServiceToken: !Ref KubeManifestLambdaArn
      # S3 path to the encrypted config file eg. s3://my-bucket/kube/config.encrypted
      KubeConfigPath: !Ref KubeConfigPath
      # context for KMS to use when decrypting the file
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      # Size of PVC used by Postgres
      PostgresPVCSize: !Ref PostgresPVCSize
      # Kubernetes manifest
      Manifest: !Sub |
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
           name: postgres-data
           annotations:
             volume.beta.kubernetes.io/storage-class: px-postgres-sc
        spec:
           accessModes:
             - ReadWriteOnce
           resources:
             requests:
               storage: '${PostgresPVCSize}'
  PostgresConfigMapStack:
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      # The lambda function that executes the manifest against the cluster. This is created in one of the parent stacks
      ServiceToken: !Ref KubeManifestLambdaArn
      # S3 path to the encrypted config file eg. s3://my-bucket/kube/config.encrypted
      KubeConfigPath: !Ref KubeConfigPath
      # context for KMS to use when decrypting the file
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      # Kubernetes manifest
      Manifest: !Sub |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: example-config
        data:
          EXAMPLE_DB_HOST: postgres://postgres@postgres/example?sslmode=disable
          EXAMPLE_DB_KIND: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
          POSTGRES_USER: postgres
  PostgresDeploymentStack:
    Type: "Custom::KubeManifest"
    Version: '1.0'
    Properties:
      # The lambda function that executes the manifest against the cluster. This is created in one of the parent stacks
      ServiceToken: !Ref KubeManifestLambdaArn
      # S3 path to the encrypted config file eg. s3://my-bucket/kube/config.encrypted
      KubeConfigPath: !Ref KubeConfigPath
      # context for KMS to use when decrypting the file
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      PostgresContainerVersion: !Ref PostgresContainerVersion
      PostgresContainerPort: !Ref PostgresContainerPort
      # Kubernetes manifest
      Manifest: !Sub |
        apiVersion: extensions/v1beta1
        kind: Deployment
        metadata:
          name: postgres
        spec:
          template:
            metadata:
              labels:
                app: postgres
            spec:
              schedulerName: stork
              containers:
              - image: "${PostgresContainerVersion}"
                name: postgres
                envFrom:
                - configMapRef:
                    name: example-config
                ports:
                - containerPort: ${PostgresContainerPort}
                  name: postgres
                volumeMounts:
                - name: postgres-data
                  mountPath: /var/lib/postgresql/data
              volumes:
              - name: postgres-data
                persistentVolumeClaim:
                  claimName: postgres-data
Outputs:
  PostgresDeploymentUid:
    Value: !GetAtt PostgresDeploymentStack.uid
